app/books/urls.py
""" URL patterns for the books app """

from django.urls import path
from . import views


app_name = 'books'
urlpatterns = [
    path('', views.index, name='index'),
    # Manage Authors
    path('authors', views.author_list, name='authors'),
    path('author/<int:author_id>/', views.author_single, name='author'),
    path('author_search', views.author_search, name='author_search'),
    path('author_add', views.author_add, name='author_add'),
    path('author_edit/<int:author_id>/', views.author_edit, name='author_edit'),
    path('author_delete/<int:author_id>/', views.author_delete, name='author_delete'),
    # Manage Books
    path('books', views.book_list, name='books'),
    path('book_search', views.book_search, name='book_search'),
    path('book_add', views.book_add, name='book_add'),
    path('book_edit/<int:book_id>/', views.book_edit, name='book_edit'),
    path('book_delete/<int:book_id>/', views.book_delete, name='book_delete'),
    # Manage Reading List
    path('reading_list', views.reading_list, name='reading_list'),
    path('reading_list_search', views.reading_list_search, name='reading_list_search'),
    path('reading_list_add/<int:book_id>/', views.reading_list_add, name='reading_list_add'),
    path('reading_list_delete/<int:book_id>/', views.reading_list_delete, name='reading_list_delete'),
]

app/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('books.urls')),
]

app/users/urls.py
""" URL patterns for the users app """

from django.urls import path, include
from . import views


app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('registration/', views.registration, name='registration'),
]

app/books/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

class Author(models.Model):
    """ The details for an author """
    name = models.CharField(max_length=200, default='', unique=True)

    def __str__(self):
        """ String representation of the model """
        return self.name

class Book(models.Model):
    """ The details for a book """
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=0)
    date_published = models.DateField()
    isbn = models.CharField(
        max_length=20,
        default="",
        validators=[
            RegexValidator(
                regex=r'^(?=(?:\D*\d){10}(?:(?:\D*\d){3})?$)[\d-]+$',
                message="Please enter a valid ISDN"
            ),
        ],
    )
    description = models.TextField(default="")

    def __str__(self):
        """ String representation of the model """
        return self.title

class Reading_List(models.Model):
    """ The items in a users reading list """
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """ String representation of the model """
        return self.owner + " " +self.book

app/books/forms.py
from django.forms import ModelForm, DateInput, TextInput
from .models import Author, Book

class DateInput(DateInput):
    input_type = 'date'

class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ['name']
        labels = {
            'name': 'Name',
        }

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'date_published', 'isbn', 'description']
        labels = {
            'title': 'Title',
            'author': 'Author',
            'date_published': 'Published',
            'isbn': 'ISBN',
            'description': 'Description',
        }
        widgets = {
            'date_published': DateInput(),
        }

app/books/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Author, Book, Reading_List
from .forms import AuthorForm, BookForm

def index(request):
    return render(request, 'books/index.html')

# Code for handling Authors
def author_list(request):
    """ Show all the authors """
    authors = Author.objects.order_by('name')
    context = {'authors': authors}
    return render(request, 'books/authors.html', context)

def author_single(request, author_id):
    """ Show a specific author and all their books """
    author = Author.objects.get(id=author_id)
    books = author.book_set.order_by('date_published')
    context = {'author': author, 'books': books}
    return render(request, 'books/author.html', context)

def author_search(request):
    """ Find Authors """
    if 'search' in request.GET:
        authors = Author.objects.all().filter(name__contains=request.GET['search']).order_by('name')
    else:
        authors = Author.objects.order_by('name')
    context = {'authors': authors}
    return render(request, 'books/authors.html', context)

@login_required
def author_add(request):
    """ Add a new author to the database """
    if request.method != 'POST':
        form = AuthorForm()
    else:
        form = AuthorForm(data=request.POST)
        if form.is_valid():
            form.save()
            if "author_add" in request.META['HTTP_REFERER']:
                return redirect('books:authors')
            else:
                return redirect(request.META['HTTP_REFERER'])

    context = {'form': form}
    return render(request, 'books/author_add.html', context)

@login_required
def author_edit(request, author_id):
    """ Edit an existing author """
    author = Author.objects.get(id=author_id)

    if request.method != 'POST':
        form = AuthorForm(instance=author)
    else:
        form = AuthorForm(instance=author, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('books:authors')

    context = {'form': form, 'author': author}
    return render(request, 'books/author_edit.html', context)

@login_required
def author_delete(request, author_id):
    """ Delete an author from the database """
    Author.objects.get(id=author_id).delete()

    return redirect('books:authors')

# Code for handling Books
def book_list(request):
    """ Show all the books """
    books = Book.objects.order_by('title')
    context = {'books': books}
    return render(request, 'books/books.html', context)

def book_search(request):
    """ Find books """
    if 'search' in request.GET:
        books = Book.objects.all().filter(title__contains=request.GET['search']).order_by('title')
    else:
        books = Book.objects.order_by('title')
    context = {'books': books}
    return render(request, 'books/books.html', context)

@login_required
def book_add(request):
    """ Add a new book to the database """
    author_form = AuthorForm()
    if request.method != 'POST':
        book_form = BookForm()
    else: 
        book_form = BookForm(data=request.POST)
        if book_form.is_valid():
            book_form.save()
            return redirect('books:books')

    context = {'author_form': author_form, 'book_form': book_form}
    return render(request, 'books/book_add.html', context)

@login_required
def book_edit(request, book_id):
    """ Edit an existing book """
    book = Book.objects.get(id=book_id)

    if request.method != 'POST':
        form = BookForm(instance=book)
    else:
        form = BookForm(instance=book, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('books:books')

    context = {'form': form, 'book': book}
    return render(request, 'books/book_edit.html', context)

@login_required
def book_delete(request, book_id):
    """ Delete an book from the database """
    Book.objects.get(id=book_id).delete()

    return redirect('books:books')

# Code for handling Reading Lists
@login_required
def reading_list(request):
    """ Show the users personal reading list """
    reading_list = Reading_List.objects.filter(owner=request.user).order_by('date_added')
    context = {'reading_list': reading_list}
    return render(request, 'books/reading_list.html', context)

@login_required
def reading_list_search(request):
    """ Find books in reading list """
    if 'search' in request.GET:
        reading_list = Reading_List.objects.filter(owner=request.user).filter(book__title__contains=request.GET['search']).order_by('book__title')
    else:
        reading_list = Reading_List.objects.filter(owner=request.user).order_by('date_added')
    context = {'reading_list': reading_list}
    return render(request, 'books/reading_list.html', context)

@login_required
def reading_list_add(request, book_id):
    """ Add to the users personal reading list """
    book = Book.objects.get(id=book_id)
    if Reading_List.objects.filter(owner=request.user).filter(book=book_id).exists():
        # This item is already in the reading list
        return redirect('books:reading_list')
    else:
        # Add the book
        new_reading = Reading_List(owner=request.user, book=book)
        new_reading.save()
        return redirect('books:reading_list')

@login_required
def reading_list_delete(request, book_id):
    """ Remove from the users personal reading list """
    Reading_List.objects.filter(owner=request.user, book=book_id).delete()
    return redirect('books:reading_list')

app/books/templates/books/author.html
{% extends "books/base.html" %}

{% block content %}
    <h3>Author: {{ author.name }}</h3>

    {% if books %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Author</th>
                    <th scope="col">Date Published</th>
                    <th scope="col">ISBN</th>
                    <th scope="col">Description</th>
                    {% if user.is_authenticated %}
                    <th scope="col">Action</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
            {% for book in books %}
                <tr>
                    <td>{{ book.title }}</td>
                    <td>{{ book.author }}</td>
                    <td>{{ book.date_published }}</td>
                    <td>{{ book.isbn }}</td>
                    <td>{{ book.description }}</td>
                    {% if user.is_authenticated %}
                    <td>
                        <a class="btn btn-success" href="{% url 'books:reading_list_add' book.id %}" role="button">Read Later</a>
                        <a class="btn btn-warning" href="{% url 'books:book_edit' book.id %}" role="button">Edit</a>
                        <a class="btn btn-danger" href="{% url 'books:author_delete' book.id %}" role="button">Delete</a>
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>There are no books for this author!</p>
    {% endif%}

{% endblock content %}

app/books/templates/books/author_add.html
{% extends "books/base.html" %}

{% block content %}
    <h3>Add a new author</h3>

    <form action="{% url 'books:author_add' %}" method='post'>
        {% csrf_token %}
        {% for item in form %}
            <label>{{ item.label }}:</label>
            <p>{{ item }}</p>
        {% endfor %}
        <button name="submit" class="btn btn-primary">Add Author</button>
    </form>
{% endblock content %}

app/books/templates/books/author_edit.html
{% extends "books/base.html" %}

{% block content %}
    <h3>Edit: {{ author.name }}</h3>

    <form action="{% url 'books:author_edit' author.id %}" method='post'>
        {% csrf_token %}
        {% for item in form %}
            <label>{{ item.label }}:</label>
            <p>{{ item }}</p>
        {% endfor %}
        <button name="submit" class="btn btn-primary">Save Changes</button>
    </form>
{% endblock content %}

app/books/templates/books/authors.html
{% extends "books/base.html" %}

{% block content %}
    <h3>Authors</h3>

    <div class="container">
        <div class="row">
            <div class="col col-xl-8">
                <a class="btn btn-primary" href="{% url 'books:author_add' %}" role="button">Add New Author</a>
            </div>
            <div class="col col-sm-4">
                <form class="d-flex" role="search" action="{% url 'books:author_search' %}" method='get'>
                    <input class="form-control me-2" type="search" name="search" placeholder="Search Authors">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </div>

    {% if authors %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
            {% for author in authors %}
                <tr>
                    <td>{{ author.name }}</td>
                    <td>
                        <a class="btn btn-success" href="{% url 'books:author' author.id %}" role="button">View</a>
                        {% if user.is_authenticated %}
                        <a class="btn btn-warning" href="{% url 'books:author_edit' author.id %}" role="button">Edit</a>
                        <a class="btn btn-danger" href="{% url 'books:author_delete' author.id %}" role="button">Delete</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No authors were found!</p>
    {% endif%}

{% endblock content %}

app/books/templates/books/base.html
{% load django_bootstrap5 %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewpoint" content="width=device-width, initial-scale=1,shrink-to-fit=no">
        <title>Book Manager</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}

        <style>
            .navbar {
                background-color: #b80000;
                margin-bottom: 10px;
            }

            .navbar-brand {
                color: #fff;
            }

            .nav-link {
                color: #fff;
            }

            .item-form {
                margin: 5px;
            }

        </style>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'books:index' %}">Book Manager</a>
                    <ul class="navbar-nav me-auto flex-row flex-wrap">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'books:authors' %}">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'books:books' %}">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'books:reading_list' %}">Personal Reading List</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-row flex-wrap ms-md-auto ">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:logout' %}">{{ user.username }}, Log Out</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:registration' %}">Create new user</a>
                            </li>
                        {% endif %}
                    </ul>
            </div>
        </nav>

        <div class="container-xl">
        {% block content %}{% endblock content %}
        </div>
    </body>

app/books/templates/books/book_add.html
{% extends "books/base.html" %}

{% block content %}
    <h3>Add a new book</h3>

    {% if book_form.errors %}
      {{ book_form.errors }}
    {% endif %}

    <div class="modal" id="authorModal" tabindex="-1">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Add New Author</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <form action="{% url 'books:author_add' %}" method='post'>
                  {% csrf_token %}
                  {{ author_form.as_p }}
                  <button name="submit" class="btn btn-primary">Add Author</button>
              </form>
            </div>
          </div>
        </div>
    </div>

    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#authorModal">
        Add New Author
    </button>

    <div class="item-form">
        <form action="{% url 'books:book_add' %}" method='post'>
            {% csrf_token %}
            {% for item in book_form %}
                <label>{{ item.label }}:</label>
                <p>{{ item }}</p>
            {% endfor %}
            <button name="submit" class="btn btn-primary">Add Book</button>
        </form>
    </div>
{% endblock content %}

app/books/templates/books/book_edit.html
{% extends "books/base.html" %}

{% block content %}
    <h3>Edit {{book.title}}</h3>

    <form action="{% url 'books:book_edit' book.id %}" method='post'>
        {% csrf_token %}
        {% for item in form %}
            <label>{{ item.label }}:</label>
            <p>{{ item }}</p>
        {% endfor %}
        <button name="submit" class="btn btn-primary">Save Changes</button>
    </form>
{% endblock content %}

app/books/templates/books/books.html
{% extends "books/base.html" %}

{% block content %}
    <h3>Books</h3>

    <div class="container">
        <div class="row">
            <div class="col col-xl-8">
                <a class="btn btn-primary" href="{% url 'books:book_add' %}" role="button">Add New Book</a>
            </div>
            <div class="col col-sm-4">
                <form class="d-flex" role="search" action="{% url 'books:book_search' %}" method='get'>
                    <input class="form-control me-2" type="search" name="search" placeholder="Search Books">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </div>

    {% if books %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Author</th>
                    <th scope="col">Date Published</th>
                    <th scope="col">ISBN</th>
                    <th scope="col">Description</th>
                    {% if user.is_authenticated %}
                        <th scope="col">Action</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
            {% for book in books %}
                <tr>
                    <td>{{ book.title }}</td>
                    <td>{{ book.author }}</td>
                    <td>{{ book.date_published }}</td>
                    <td>{{ book.isbn }}</td>
                    <td>{{ book.description }}</td>
                    {% if user.is_authenticated %}
                    <td>
                        <a class="btn btn-success" href="{% url 'books:reading_list_add' book.id %}" role="button">Read Later</a>
                        <a class="btn btn-warning" href="{% url 'books:book_edit' book.id %}" role="button">Edit</a>
                        <a class="btn btn-danger" href="{% url 'books:book_delete' book.id %}" role="button">Delete</a>
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No books were found!</p>
    {% endif%}

{% endblock content %}

app/books/templates/books/index.html
{% extends "books/base.html" %}

{% block content %}
    <h3>Keep track of your books</h3>
    <p>The book manager allows you to browse a collection of books and authors.</p>
    <p>By making an account you can add to the collection of books and authors and even build your own custom reading list</p>
{% endblock content %}

app/books/templates/books/reading_list.html
{% extends "books/base.html" %}

{% block content %}
    <h3>Your Reading List</h3>

    {% if reading_list %}
    <div class="container">
        <div class="row">
            <div class="col col-xl-8">
            </div>
            <div class="col col-sm-4">
                <form class="d-flex" role="search" action="{% url 'books:reading_list_search' %}" method='get'>
                    <input class="form-control me-2" type="search" name="search" placeholder="Search Reading List">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </div>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Author</th>
                    <th scope="col">Date Added</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
            {% for item in reading_list %}
                <tr>
                    <td>{{ item.book.title }}</td>
                    <td>{{ item.book.author }}</td>
                    <td>{{ item.date_added }}</td>
                    <td><a class="btn btn-danger" href="{% url 'books:reading_list_delete' item.book.id %}" role="button">Remove</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No books were found in your reading list!</p>
    {% endif%}

{% endblock content %}